version: '3.8'

services:
  auth_service:
    build: 
      context: ./auth_services
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_sECRET={GITHUB_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - ALLOWED_HOSTS=["*"]
    depends_on:
      - redis
    networks:
      - flixshare-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/auth/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

  room_service:
    build:
      context: ./room_management
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - AUTH_BACKEND_URL=http://auth_service:8000
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MPESA_CONSUMER_KEY=${MPESA_CONSUMER_KEY}
      - MPESA_CONSUMER_SECRET=${MPESA_CONSUMER_SECRET}
      - MPESA_PASSKEY=${MPESA_PASSKEY}
      - MPESA_CALLBACK_URL=${MPESA_CALLBACK_URL}
      - ALLOWED_HOSTS=["*"]
    depends_on:
      - redis
      - auth_service
    networks:
      - flixshare-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - flixshare-network

networks:
  flixshare-network:
    driver: bridge